package com.shinhan.day08;

public class ExceptionTest {
	public static void main(String[] args) {
		method1(10);
	}

	private static void method1(int count) {
		//예외 : 1)RuntimeException...실행 시 오류발생 2)일반Exception
		int score = 100;
		int[] arr = new int[10];
		
		//if(count == 0) return;
		//오류처리로직과 비즈니스로직 처리가 섞인다. 권장하지 않음
		
		try {
			System.out.println("평균은 " + score/count);
			arr[0] =99;
			System.out.println(arr[10]);
		} catch(ArithmeticException ex) {
			//Exception 처리함...그러므로 프로그램 중단없이 계속 진행된다.
			System.out.println("연산오류....." + ex.getMessage());
		} catch(NullPointerException ex) {
			//Exception 처리함...그러므로 프로그램 중단없이 계속 진행된다.
			System.out.println("연산오류....." + ex.getMessage());
		} catch(ArrayIndexOutOfBoundsException ex) {
			//Exception 처리함...그러므로 프로그램 중단없이 계속 진행된다.
			System.out.println("연산오류....." + ex.getMessage());
		} finally {
			System.out.println("오류가 있거나 없거나 무조건 수행하는 업무이다.");
		}
		System.out.println("-----------------------------------------");
	}
}
